Keycloak 17 had major changes that affect setup.
latchset/federation_testing pull request #13
Opened 2022-06-15 17:31 UTC by spoore1

container must now be started with more options to specify https config
properly.

a truststore must also be configured

in newer versions of keycloak, ECP flow is not enabled by default.
Adding commands to enable that in test_mellon.sh before tests run.

Also changing kcadm path and server url for khci test script.

Modify khci test script to check for testuser before creating.

2022-06-15 18:13 UTC, spoore1 commented
@vashirov can you review this PR?

2022-06-15 19:00 UTC, vashirov commented
`test_web_sso_post_redirect` fails for me:

```

================================================================== FAILURES ===================================================================
_________________________________________________________ test_web_sso_post_redirect __________________________________________________________

login_user = ('testuser', 'Secret123'), resource_url = 'https://redacted.example.com:60443/mellon_root/private/'
saml_test_instance = <samltest.SamlLoginTest object at 0x7fefbfacb3c8>

    def test_web_sso_post_redirect(login_user, resource_url, saml_test_instance):
        """Test the web browser SSO profile

        :id: ffcd9c05-34b3-4aa4-91a6-279c9cbc3613
        :steps:
            1. Run the WebSSO for resource_url flow with an empty session
            2. Reuse cached session and check page for redirects
            3. Clear session
            4. Check that page contains IdP auth redirect
        :expectedresults:
            1. Success
            2. Page should be without redirects
            3. Success
            4. Response should contain redirect to the IdP auth page
        """
        logging.info(f"About to run the WebSSO flow for {resource_url} with "
                      "an empty session")
        username, password = login_user
        saml_test_instance.redirect_post_flow(resource_url,
                                              username,
                                              password,
>                                             is_my_page)

test_mellon.py:76:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
samltest.py:454: in redirect_post_flow
    saml_response = self.idp_factory.saml_response_parser(login_reply)
samltest.py:388: in saml_response_parser
    saml_response.from_reply(reply)
samltest.py:199: in from_reply
    return self.from_form(reply.text)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <samltest.KeycloakSamlResponse object at 0x7fefbfae8e80>
html_form = '<!DOCTYPE html>\n<html class="login-pf">\n\n<head>\n    <meta charset="utf-8">\n    <meta http-equiv="Content-Type" c...orm>\n        </div>\n\n    </div>\n\n\n\n\n\n        </div>\n      </div>\n\n    </div>\n  </div>\n</body>\n</html>\n'

    def from_form(self, html_form):
        print(html_form)
        parser = AttrHTMLParser(html_form)

        rstate_input = parser.find_tag('input',
                                       required_attrs={'name': 'RelayState'})
>       self.relay_state = rstate_input.get('value')
E       AttributeError: 'NoneType' object has no attribute 'get'

samltest.py:271: AttributeError
------------------------------------------------------------ Captured stdout setup ------------------------------------------------------------
https://redacted.example.com:8443/auth/realms/khci.test/protocol/saml
------------------------------------------------------------ Captured stdout call -------------------------------------------------------------
<!DOCTYPE html>
<html class="login-pf">

<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="robots" content="noindex, nofollow">

            <meta name="viewport" content="width=device-width,initial-scale=1"/>
    <title>Sign in to khci.test</title>
    <link rel="icon" href="/auth/resources/zvvs8/login/keycloak/img/favicon.ico" />
            <link href="/auth/resources/zvvs8/common/keycloak/web_modules/@patternfly/react-core/dist/styles/base.css" rel="stylesheet" />
            <link href="/auth/resources/zvvs8/common/keycloak/web_modules/@patternfly/react-core/dist/styles/app.css" rel="stylesheet" />
            <link href="/auth/resources/zvvs8/common/keycloak/node_modules/patternfly/dist/css/patternfly.min.css" rel="stylesheet" />
            <link href="/auth/resources/zvvs8/common/keycloak/node_modules/patternfly/dist/css/patternfly-additions.min.css" rel="stylesheet" />
            <link href="/auth/resources/zvvs8/common/keycloak/lib/pficon/pficon.css" rel="stylesheet" />
            <link href="/auth/resources/zvvs8/login/keycloak/css/login.css" rel="stylesheet" />
            <link href="/auth/resources/zvvs8/login/keycloak/css/tile.css" rel="stylesheet" />
<SCRIPT> if (typeof history.replaceState === 'function') {  history.replaceState({}, "some title", "https://redacted.example.com:8443/auth/realms/khci.test/login-actions/authenticate?execution=922f863d-3041-42bd-8e90-4a78fb556bda&client_id=https%3A%2F%2Fredacted.example.com%3A60443%2Fmellon_root%2Fmellon%2Fmetadata&tab_id=c1FVxEa8zcs"); }</SCRIPT></head>

<body class="">
<div class="login-pf-page">
    <div id="kc-header" class="login-pf-page-header">
        <div id="kc-header-wrapper"
             class="">khci.test</div>
    </div>
    <div class="card-pf">
        <header class="login-pf-header">
                <h1 id="kc-page-title">        Sign in to your account

</h1>
      </header>
      <div id="kc-content">
        <div id="kc-content-wrapper">


    <div id="kc-form">
      <div id="kc-form-wrapper">
            <form id="kc-form-login" onsubmit="login.disabled = true; return true;" action="https://redacted.example.com:8443/auth/realms/khci.test/login-actions/authenticate?session_code=7nsuOT1fPAwYjwd2Kkeln3BjMVIBOpDDAkIN7xRCy20&amp;execution=922f863d-3041-42bd-8e90-4a78fb556bda&amp;client_id=https%3A%2F%2Fredacted.example.com%3A60443%2Fmellon_root%2Fmellon%2Fmetadata&amp;tab_id=c1FVxEa8zcs" method="post">
                    <div class="form-group">
                        <label for="username" class="pf-c-form__label pf-c-form__label-text">Username or email</label>

                        <input tabindex="1" id="username" class="pf-c-form-control" name="username" value="testuser"  type="text" autofocus autocomplete="off"
                               aria-invalid="true"
                        />

                            <span id="input-error" class="pf-c-form__helper-text pf-m-error required kc-feedback-text" aria-live="polite">
                                    Invalid username or password.
                            </span>

                    </div>

                <div class="form-group">
                    <label for="password" class="pf-c-form__label pf-c-form__label-text">Password</label>

                    <input tabindex="2" id="password" class="pf-c-form-control" name="password" type="password" autocomplete="off"
                           aria-invalid="true"
                    />


                </div>

                <div class="form-group login-pf-settings">
                    <div id="kc-form-options">
                        </div>
                        <div class="">
                        </div>

                  </div>

                  <div id="kc-form-buttons" class="form-group">
                      <input type="hidden" id="id-hidden-input" name="credentialId" />
                      <input tabindex="4" class="pf-c-button pf-m-primary pf-m-block btn-lg" name="login" id="kc-login" type="submit" value="Sign In"/>
                  </div>
            </form>
        </div>

    </div>





        </div>
      </div>

    </div>
  </div>
</body>
</html>

```
It seems that the testuser is not logged in?

2022-06-21 13:42 UTC, spoore1 commented
What Distro/release are you testing on?   I tried on RHEL9, RHEL8, and Fedora 36 and I don't see that error.

Was there anything from the setup.sh that looked off that may indicate that Keycloak wasn't fully running at the time?

2022-06-27 10:52 UTC, vashirov commented
I tried this on RHEL8 and RHEL9 (in 1MT). I see messages that connection to port 8080 is refused:
```
++ curl -q -XPOST http://localhost:8080/auth/realms/master/protocol/openid-connect/token '-dgrant_type=password&username=admin&password=Secret123&client_id=admin-cli'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0++ jq .access_token
curl: (7) Failed to connect to localhost port 8080: Connection refused
+ TOKEN=
++ curl -v '-w%{response_code}' '-HBearer: ' http://localhost:8080/realms/khci.test
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8080 failed: Connection refused
* Failed to connect to localhost port 8080: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8080: Connection refused

```

After inspecting the running container, it appears that there is nothing running on port 8080. Turns out HTTP is disabled by default. I've added an env variable to enable it back.
```diff
diff --git a/setup.sh b/setup.sh
index 206846c..91bf8b8 100755
--- a/setup.sh
+++ b/setup.sh
@@ -209,6 +209,7 @@ podman run --name keycloak -d \
     -e KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key \
     -e KC_HTTPS_TRUST_STORE_FILE=/etc/x509/https/truststore.keystore \
     -e KC_HTTPS_TRUST_STORE_PASSWORD=Secret123 \
+    -e KC_HTTP_ENABLED=true \
     -e KC_HTTP_RELATIVE_PATH=/auth \
     -v /tmp/https:/etc/x509/https:Z \
     quay.io/keycloak/keycloak:$KC_VERSION start --auto-build

```

But even with these changes if fails further down the road:
```
curl -v '-w%{response_code}' '-HBearer: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJVUGY3d1dhNVoyVS1nS3Jqc1JCQVRPOHlDcGJDWXczOHFSNWZTeG5MYXdNIn0.eyJleHAiOjE2NTYzMjY2MTUsImlhdCI6MTY1NjMyNjU1NSwianRpIjoiMGFjNTI1MmMtMDFlZi00YmVkLTljZjgtMWE5YTJhYTM4NzMwIiwiaXNzIjoiaHR0cHM6Ly9jaS12bS0xMC0wLTEzOC0yMDMuaG9zdGVkLnVwc2hpZnQucmR1Mi5yZWRoYXQuY29tOjg0NDMvYXV0aC9yZWFsbXMvbWFzdGVyIiwic3ViIjoiNTQ0YmNkZWMtNzRhNC00MmE0LWJmNmEtOWNmOGU4YzAxZTllIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYWRtaW4tY2xpIiwic2Vzc2lvbl9zdGF0ZSI6IjM4NGZkYTIzLTAxN2YtNDljYS1hNTQ0LTFkN2ExYjJjZjNhZCIsImFjciI6IjEiLCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiIzODRmZGEyMy0wMTdmLTQ5Y2EtYTU0NC0xZDdhMWIyY2YzYWQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIn0.BgdI58CcuATQL4_ilNexC1xEamqGbrcrFpYKZXWOjz1OiDfiFn1Qjz26Ilhpmpfu_qVE2zt9pTNrYlnv3-Wj0Nsr8qNL2vaptrUJfS-k6DZXRHQA9oUhe-Aev-BvSIwNHI9hFkA8EmoCwadeyqtV5rBuqqHuK5q4CG7x3g9ZX1AGm93kXJaBTYwDGBV5TvjJFuBu4qRPqIQcNaJW3ojDOCbG2ylNL1Q5k7V3BtbEG1KV-D2oOwBY_9IDbY9v4Q90RJ2IfkXwsnqFidTyuI9dhFIGsowNajy_NNmEmJWL7ipw7JrC2v5pzE1vMbcUUkRqUM3FdL5EFCjYpn5aq1AnkQ"' http://localhost:8080/realms/khci.test
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /realms/khci.test HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.61.1
> Accept: */*
> Bearer: "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJVUGY3d1dhNVoyVS1nS3Jqc1JCQVRPOHlDcGJDWXczOHFSNWZTeG5MYXdNIn0.eyJleHAiOjE2NTYzMjY2MTUsImlhdCI6MTY1NjMyNjU1NSwianRpIjoiMGFjNTI1MmMtMDFlZi00YmVkLTljZjgtMWE5YTJhYTM4NzMwIiwiaXNzIjoiaHR0cHM6Ly9jaS12bS0xMC0wLTEzOC0yMDMuaG9zdGVkLnVwc2hpZnQucmR1Mi5yZWRoYXQuY29tOjg0NDMvYXV0aC9yZWFsbXMvbWFzdGVyIiwic3ViIjoiNTQ0YmNkZWMtNzRhNC00MmE0LWJmNmEtOWNmOGU4YzAxZTllIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYWRtaW4tY2xpIiwic2Vzc2lvbl9zdGF0ZSI6IjM4NGZkYTIzLTAxN2YtNDljYS1hNTQ0LTFkN2ExYjJjZjNhZCIsImFjciI6IjEiLCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJzaWQiOiIzODRmZGEyMy0wMTdmLTQ5Y2EtYTU0NC0xZDdhMWIyY2YzYWQiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6ImFkbWluIn0.BgdI58CcuATQL4_ilNexC1xEamqGbrcrFpYKZXWOjz1OiDfiFn1Qjz26Ilhpmpfu_qVE2zt9pTNrYlnv3-Wj0Nsr8qNL2vaptrUJfS-k6DZXRHQA9oUhe-Aev-BvSIwNHI9hFkA8EmoCwadeyqtV5rBuqqHuK5q4CG7x3g9ZX1AGm93kXJaBTYwDGBV5TvjJFuBu4qRPqIQcNaJW3ojDOCbG2ylNL1Q5k7V3BtbEG1KV-D2oOwBY_9IDbY9v4Q90RJ2IfkXwsnqFidTyuI9dhFIGsowNajy_NNmEmJWL7ipw7JrC2v5pzE1vMbcUUkRqUM3FdL5EFCjYpn5aq1AnkQ"
>
< HTTP/1.1 404 Not Found
< content-type: text/html; charset=utf-8
< content-length: 53
<
* Connection #0 to host localhost left intact
<html><body><h1>Resource not found</h1></body></html>404
```

2022-06-27 13:40 UTC, vashirov commented
Ignore the last failure, this is expected, as it checks for the existence of the realm. But still, the test fails with khci.test realm and passes with the default one.

2022-06-27 14:00 UTC, vashirov commented
Ok, with this change the test works:

```diff
diff --git a/test_khci.sh b/test_khci.sh
index 5c2a9e8..ec2c69b 100755
--- a/test_khci.sh
+++ b/test_khci.sh
@@ -100,7 +100,7 @@ kcadm="podman exec keycloak /opt/keycloak/bin/kcadm.sh"
 $kcadm config credentials --server https://$(hostname):8443/auth/ \
         --realm master --user admin --password Secret123

-USERID=$($kcadm get users|jq -r '.[]|select(.username=="testuser").id')
+USERID=$($kcadm get users -r $NEW_REALM | jq -r '.[]|select(.username=="testuser").id')
 if [ -z "$USERID" ]; then
     $kcadm create users -r $NEW_REALM -s username=testuser -s enabled=true
     $kcadm set-password -r $NEW_REALM --username testuser --new-password Secret123

```

User `testuser` was missing in the new realm.

2022-07-01 07:06 UTC, vashirov requested changes
With the proposed change test works for me.

2022-07-01 07:06 UTC, vashirov commented on test_khci.sh
> +USERID=$($kcadm get users|jq -r '.[]|select(.username=="testuser").id')
```suggestion
USERID=$($kcadm get users -r $NEW_REALM | jq -r '.[]|select(.username=="testuser").id')
```

2022-07-01 13:01 UTC, spoore1 commented
AH, I must have been skipping the khci test.   I've committed your suggestion.   Any other suggestions before I merge it?

2022-07-01 14:22 UTC, merged